wiki/encyclopedia/urls.py
from django.urls import path
from . import util

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.redirect, name="base"),
    path("wiki/", views.index, name="index"),
    path("wiki/new", views.new_wiki, name="new_wiki"),
    path("wiki/edit", views.edit_wiki_list, name="edit_wiki_list"),
    path("wiki/edit/<str:page_name>", views.edit_wiki, name="edit_wiki"),
    path("wiki/random", views.random_page, name="random_page"),
    path("search/", views.search, name="search"),
    path("wiki/<str:page_name>", views.render_page, name="render_page")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import random

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse

from . import util

import markdown2


class SearchForm(forms.Form):
    searched = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'search'}))

class NewPageForm(forms.Form):
    new_name = forms.CharField()
    markdown_text = forms.CharField()


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm()
    })

def redirect(request):
    return HttpResponseRedirect("wiki/")
def render_page(request, page_name):

    if page_name in util.list_entries():
        return render(request, "encyclopedia/index_wiki.html", {
            "page_name": page_name,
            "mark_content": markdown2.markdown(util.get_entry(page_name)),
            "form": SearchForm()
        })
    else:
        return render(request, "encyclopedia/index_wiki.html", {
            "page_name": page_name,
            "mark_content": "<h1>" + page_name + "</h1><p>The requested page was not found!</p>",
            "form": SearchForm()
        })


def search_in_page(entry_name: str, searched: str, founds: dict):
    page = util.get_entry(entry_name)
    page = page.strip('\r')

    temp_dic = {entry_name: []}
    for ln in page.split('\n'):
        if searched.upper() in ln.upper():
            temp_dic[entry_name].append(ln)

    if len(temp_dic[entry_name]):
        founds[entry_name] = temp_dic[entry_name]

def render_results(founds: dict) -> str:
    html = ''
    for name, values in founds.items():
        html += f'<div><a href="/wiki/{name}"><b>{name}</b>'

        for ln in values:
            html += f'<div>{markdown2.markdown(ln)}</div>'

        html += '</a></div>'

    return html


def search(request):
    # Check if method is POST
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = SearchForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            searching = form.cleaned_data["searched"]

            # If the query matches the name of an encyclopedia entry, the user should be redirected
            # to that entry’s page.
            for x in util.list_entries():
                if searching.upper() == x.upper():
                    return render(request, "encyclopedia/index_wiki.html", {
                        "page_name": x,
                        "mark_content": markdown2.markdown(util.get_entry(x)),
                        "form": SearchForm()
                    })

            # If the query does not match the name of an encyclopedia entry, the user should instead
            # be taken to a search results page that displays a list of all encyclopedia entries that
            # have the query as a substring. For example, if the search query were ytho, then Python
            # should appear in the search results.
            founds = {}
            for x in util.list_entries():
                search_in_page(x, searching, founds)

            if founds:
                # Show page's results
                return render(request, "encyclopedia/index_wiki.html", {
                    "page_name": "Search results: ",
                    "mark_content": render_results(founds),
                    "form": SearchForm()
                })
            else:
                # Show page's no results
                return render(request, "encyclopedia/index_wiki.html", {
                    "page_name": "Search results: ",
                    "mark_content": f"<h1>Search results!</h1><p>No results for {searching}!</p>",
                    "form": SearchForm()
                })
    else:
        return HttpResponseRedirect(reverse("wiki:index"))

def new_wiki(request):
    # Check if method is POST
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewPageForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            new_name = form.cleaned_data["new_name"]
            markdown_text = form.cleaned_data["markdown_text"]

            for x in util.list_entries():
                if new_name.upper() == x.upper():
                    return render(request, "encyclopedia/index_new.html", {
                        "page_name": "New wiki page",
                        "action_url": reverse("wiki:new_wiki"),
                        "message": f'The new wiki page exists: <a href="/wiki/{x}">{x}</a>',
                        "new_name": x,
                        "mark_content": markdown_text,
                        "form": SearchForm(),
                        "button_text": "Save new wiki"
                    })

            util.save_entry(new_name, markdown_text)
            return render_page(request, new_name)

    return render(request, "encyclopedia/index_new.html", {
        "page_name": "New wiki page",
        "action_url": reverse("wiki:new_wiki"),
        "message": "Creating a new wiki page!",
        "new_name": "",
        "mark_content": "",
        "form": SearchForm(),
        "button_text": "Save new wiki"
    })

def random_page(request):
    page_name = random.choice(util.list_entries())
    return render_page(request, page_name)

def edit_wiki_list(request):
    return render(request, "encyclopedia/index_edit_list.html", {
        "page_name": "Edit wiki page",
        "message": "Select wiki page to edit",
        "entries": util.list_entries(),
        "form": SearchForm()
    })

def edit_wiki(request, page_name):
    # Check if method is POST
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewPageForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            new_name = form.cleaned_data["new_name"]
            markdown_text = form.cleaned_data["markdown_text"]

            for x in util.list_entries():
                if new_name.upper() == x.upper():
                    util.save_entry(x, markdown_text)
                    return render_page(request, x)


            util.save_entry(new_name, markdown_text)
            return render_page(request, new_name)

    if page_name == '':
        # Redirect user to page's edit wiki
        # if the name of wiki page to edit is empty
        return HttpResponseRedirect(reverse("wiki:edit_wiki_list"))
    elif page_name in util.list_entries():
        return render(request, "encyclopedia/index_new.html", {
            "page_name": "Editing wiki page",
            "action_url": f'/wiki/edit/{page_name}',
            "message": f'Editing page: <a href="/wiki/{page_name}">{page_name}</a>',
            "new_name": page_name,
            "mark_content": util.get_entry(page_name).replace('\r', ''),
            "form": SearchForm(),
            "button_text": "Save edit wiki"
        })
    else:
        # Displays the message that the wiki does not exist
        # if the user tries to edit a page that does not exist
        return render(request, "encyclopedia/index_new.html", {
            "page_name": "Wiki does not exists",
            "action_url": reverse("wiki:new_wiki"),
            "message": f"Wiki does not exists: <b>{page_name}</b>, but you can create a new!",
            "new_name": page_name,
            "mark_content": f"# {page_name}",
            "form": SearchForm(),
            "button_text": "Save edit wiki"
        })

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    Encyclopedia
{% endblock %}

{% block nav %}
    {% include "encyclopedia/left_bar.html" %}
{% endblock %}


{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index_edit_list.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    Encyclopedia: {{page_name}}
{% endblock %}

{% block nav %}
    {% include "encyclopedia/left_bar.html" %}
{% endblock %}


{% block body %}
    <h1>{{message}}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="edit/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index_new.html
{% extends "encyclopedia/layout_wiki.html" %}

{% block title %}
    Encyclopedia: {{page_name}}
{% endblock %}

{% block nav %}
    {% include "encyclopedia/left_bar.html" %}
{% endblock %}

{% block body %}
    {% if message %}
        <h1> {{ message|safe }} </h1>
    {% endif %}
<div id="new_wiki">
    <form action="{{ action_url }}" method="post">
        {% csrf_token %}
                <div>
                    <label for="as_title">Title:</label>
                    <input value="{{ new_name}}" autofocus="autofocus" id="as_title" name="new_name" type="text">
                    <label class="label_rigth">Type the title of the new wiki page</b></label>
                </div>
                <div>
                    <label for="as_content">Markdown text:</label>
                    <textarea id="as_content" name="markdown_text">{{ mark_content }}</textarea>
                    <label class="label_rigth">Markdown text for new wiki page</b></label>
                </div>
            <div>
                <div></div>
                <button type="submit">{{ button_text }}</button>
            </div>
        </form>
</div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index_wiki.html
{% extends "encyclopedia/layout_wiki.html" %}


{% block nav %}
    {% include "encyclopedia/left_bar.html" %}
{% endblock %}

{% block title %}
    Encyclopedia: {{page_name}}
{% endblock %}

{% block body %}

{{ mark_content|safe }}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/layout_new.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/layout_wiki.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/left_bar.html
    <h2>Wiki</h2>
    <form action="{% url 'wiki:search' %}" method="post">
        {% csrf_token %}
        {{ form }}
    </form>
    <div>
        <a href="{% url 'wiki:index' %}">Home</a>
    </div>
    <div>
        <a href="/wiki/new">Create New Page</a>
    </div>
    <div>
        <a href="/wiki/edit">Edit Page</a>
    </div>
    <div>
        <a href="/wiki/random">Random Page</a>
    </div>