capstone/courier/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    # Users
    path("users/", views.users_list, name="users-list"),
    # Profile
    path("profile/", views.profile_view, name="profile"),
    path("profile/address/add/", views.address_add, name="add-address"),
    path("profile/address/update/", views.address_update, name="update-address"),
    path("profile/address/remove/", views.address_remove, name="remove-address"),
    path("profile/phone/add/", views.phone_add, name="add-phone"),
    path("profile/phone/update/", views.phone_update, name="update-phone"),
    path("profile/phone/remove/", views.phone_remove, name="remove-phone"),
    # Shipments
    path("shipments/new", views.shipments_new, name="new-shipment"),
    path("shipments/cancel", views.shipments_cancel, name="cancel-shipment"),
    path("shipments/receipt", views.shipments_receipt, name="receipt-shipment"),
    path("shipments/deliver", views.shipments_deliver, name="deliver-shipment"),
    # Courier
    path("courier/", views.courier_view, name="courier-view"),
    path("courier/order", views.courier_order, name="courier-order"),
    path("courier/receive", views.courier_receive, name="courier-receive"),
    path("courier/deliver", views.courier_deliver, name="courier-deliver"),
    path("courier/delivered", views.courier_delivered, name="courier-delivered"),
]

capstone/final_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("courier.urls")),
]

capstone/courier/models.py
import random

from django.db import models

from django.utils import timezone

from django.contrib.auth.models import User as auth_User

phone_max_length = 20


class User(auth_User):
    is_courier = models.BooleanField(default=False)

    def serialize(self):
        return {
            "id": self.id,
            "username": self.username,
            "first_name": self.first_name,
            "last_name": self.last_name,
            "email": self.email,
            "phones_num": self.phones.count(),
            "addresses_num": self.addresses.count(),
            "phones": [phone.serialize() for phone in self.phones.all()],
            "addresses": [address.serialize() for address in self.addresses.all()],
        }

    def list_for_shipment(self):
        return [address.user for address in self.addresses.all()]


class PhoneNumber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="phones")
    phone_number = models.CharField(max_length=phone_max_length)

    def serialize(self):
        return {
            "id": self.id,
            "phone_number": self.phone_number
        }


class GPSPosition(models.Model):
    latitude = models.FloatField(null=False)
    longitude = models.FloatField(null=False)
    date_time = models.DateTimeField(default=timezone.now)

    def serialize(self):
        return {'latitude': self.latitude, 'longitude': self.longitude}


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="addresses")
    address = models.CharField(max_length=200)
    complement = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    gps = models.ForeignKey(GPSPosition, null=True, on_delete=models.CASCADE, related_name="address_positions")

    def serialize(self):
        if self.gps:
            return {
                "id": self.id,
                "address": self.address,
                "complement": self.complement,
                "city": self.city,
                "gps": self.gps.serialize()
            }
        else:
            return {
                "id": self.id,
                "address": self.address,
                "complement": self.complement,
                "city": self.city
            }


class Shipment(models.Model):
    CREATED = 0
    ORDERED = 1
    PICK_UP = 2
    DELIVERED = 3
    CANCELED = 4

    SHIPMENT_STATUS = (
        (CREATED, 'Created'),
        (ORDERED, 'Ordered'),
        (PICK_UP, 'Pick up order'),
        (DELIVERED, 'Delivered'),
        (CANCELED, 'Canceled'))

    contents = models.CharField(max_length=200)
    check_code_get = models.CharField(max_length=10, null=True)
    check_code_put = models.CharField(max_length=10, null=True)
    user_courier = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name="couriers")
    user_sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="senders")
    address_sender = models.ForeignKey(Address, on_delete=models.CASCADE, related_name="get_place")
    user_receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receivers")
    address_receiver = models.ForeignKey(Address, on_delete=models.CASCADE, related_name="put_place")
    chat_id = models.CharField(max_length=10, null=True)
    datetime_create = models.DateTimeField(default=timezone.now)
    status = models.IntegerField(default=0,
                                 choices=SHIPMENT_STATUS)

    def serialize(self):
        result = {
            "id": self.id,
            "contents": self.contents,
            "check_code_get": self.check_code_get,
            "check_code_put": self.check_code_put,
            "user_sender": self.user_sender.serialize(),
            "user_receiver": self.user_receiver.serialize(),
            "address_sender": self.address_sender.serialize(),
            "address_receiver": self.address_receiver.serialize()}
        if self.user_courier:
            result["courier"] = self.user_courier.serialize()

        result["status"] = self.SHIPMENT_STATUS[self.status][1]
        result["status_id"] = self.SHIPMENT_STATUS[self.status][0]

        return result


class Deliver(models.Model):
    shipment = models.ForeignKey(Shipment, null=False, on_delete=models.CASCADE, related_name="deliver_shipments")
    datetime_create = models.DateTimeField(default=timezone.now)
    gps = models.ForeignKey(GPSPosition, null=True, on_delete=models.CASCADE, related_name="deliver_positions")


def make_code(user1: User, user2: User, ship: Shipment) -> str:
    random.seed(user1.id * ship.id + user2.id)

    code = ''
    for digit in range(4):
        code += str(random.randint(0, 9))
    return code

capstone/courier/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms

from courier.models import phone_max_length

from courier.models import (PhoneNumber,
                            Address,
                            GPSPosition,
                            User,
                            Shipment,
                            make_code)

from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required

from django.http import JsonResponse
import json


def get_user(request):
    return User.objects.get(username=request.user.username)


def get_shipments_courier(request, status=None):
    print(f"get_shipments_courier status= {status} Shipment.CREATED={Shipment.CREATED} == {status == Shipment.CREATED}")
    if status == None:
        return [ship.serialize() for ship in get_user(request).couriers.all()]
    else:
        if status == Shipment.CREATED:
            print(True)
            print([ship.serialize() for ship in Shipment.objects.filter(status=status).exclude(user_sender=get_user(request))])
            return [ship.serialize() for ship in Shipment.objects.filter(status=status).exclude(user_sender=get_user(request))]
        else:
            print(False)
            return [ship.serialize() for ship in get_user(request).couriers.filter(status=status)]


def is_courier(request):
    try:
        return get_user(request).is_courier
    except:
        return False


class LoginForm(forms.Form):
    username = forms.CharField(label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "User name", "autofocus": ""}))
    password = forms.CharField(label="",
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))


@csrf_protect
def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("index"))

    if request.method == "POST":
        # Receives the user registration data sent to register the user
        form = LoginForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # Attempt to user login
            user = authenticate(request, username=username, password=password)

            # Check if authentication successful
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))

        return render(request, "courier/login.html", {
            "message": "Invalid username and/or password.",
            "form": form
        })
    else:
        return render(request, "courier/login.html", {
            "form": LoginForm})


@login_required(login_url='/login/')
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("login"))


class UserForm(forms.Form):
    username = forms.CharField(required=True, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "User name", "autofocus": ""}))
    firstname = forms.CharField(required=True, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "First name", "autofocus": ""}))
    lastname = forms.CharField(required=True, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "Last name", "autofocus": ""}))
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "Email"}))
    password = forms.CharField(required=True, label="", widget=forms.PasswordInput(
        attrs={"class": "form-control", "placeholder": "Password"}))
    confirmation = forms.CharField(required=True, label="", widget=forms.PasswordInput(
        attrs={"class": "form-control", "placeholder": "Confirm Password"}))
    is_courier = forms.BooleanField(required=False, widget=forms.CheckboxInput())


class PhoneForm(forms.Form):
    phone_number = forms.CharField(required=True, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "Phone number"}),
                                   max_length=phone_max_length)


class AddressForm(forms.Form):
    address = forms.CharField(required=True, label="", widget=forms.Textarea(
        attrs={"class": "form-control", "rows": 3, "placeholder": "Address"}))
    complement = forms.CharField(required=False, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "Address complement"}))
    city = forms.CharField(required=True, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "City"}))
    gps_latitude = forms.FloatField(required=False, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "Latitude"}))
    gps_longitude = forms.FloatField(required=False, label="", widget=forms.TextInput(
        attrs={"class": "form-control", "placeholder": "Longitude"}))


class RegisterForm(AddressForm, PhoneForm, UserForm):
    pass


def create_address(user, address, complement, city, gps):
    try:
        if complement and gps:
            Address(user=user, address=address, complement=complement, city=city, gps=gps).save()
        elif complement:
            Address(user=user, address=address, complement=complement, city=city).save()
        elif gps:
            Address(user=user, address=address, city=city, gps=gps).save()
        else:
            Address(user=user, address=address, city=city).save()
    except Exception as e:
        return f"Error creating new address: {e}"
    else:
        return None


@csrf_protect
def register_view(request):
    if request.method == "POST":
        # Receives the user registration data sent to register the user
        form = RegisterForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Ensure password matches confirmation
            password = form.cleaned_data["password"]
            confirmation = form.cleaned_data["confirmation"]
            if password != confirmation:
                form.add_error('confirmation', 'Passwords must match.')
                return render(request, "courier/index.html", {
                    "title": "New Profile",
                    "form": form,
                    "message": "Passwords must match."
                }, status=400)

            latitude = form.cleaned_data['gps_latitude']
            longitude = form.cleaned_data['gps_longitude']
            gps = None
            if latitude and longitude:
                gps = GPSPosition(latitude=latitude, longitude=longitude)
                gps.save()
            elif latitude:
                form.add_error('gps_longitude', 'Longitude error!')
                return render(request, "courier/index.html", {
                    "title": "New Profile",
                    "message": "<p>Invalid register information:</p>" + str(form.errors),
                    "form": form}, status=400)
            elif longitude:
                form.add_error('gps_latitude', 'Latidude error!')
                return render(request, "courier/index.html", {
                    "title": "New Profile",
                    "message": "<p>Invalid register information:</p>" + str(form.errors),
                    "form": form}, status=400)
            # Attempt to create new user
            try:
                username = form.cleaned_data['username']
                firstname = form.cleaned_data['firstname']
                lastname = form.cleaned_data['lastname']
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                is_courierl = form.cleaned_data['is_courier']
                user = User.objects.create_user(username=username, email=email,
                                                password=password, is_courier=is_courierl,
                                                first_name=firstname, last_name=lastname)
                user.save()
            except Exception as e:
                return render(request, "courier/index.html", {
                    "title": "New Profile",
                    "form": form,
                    "message": f"Error creating new user: {e}"
                }, status=400)

            PhoneNumber(user=user, phone_number=form.cleaned_data['phone_number']).save()

            # Create a new address
            msg = create_address(user=user,
                                 address=form.cleaned_data['address'],
                                 complement=form.cleaned_data['complement'],
                                 city=form.cleaned_data['city'],
                                 gps=gps)
            if msg:
                return render(request, "courier/index.html", {
                    "title": "New Profile",
                    "form": form,
                    "message": msg
                }, status=400)
            else:
                return redirect("login")

        else:
            return render(request, "courier/index.html", {
                "title": "New Profile",
                "message": "<p>Invalid register information:</p>" + str(form.errors),
                "form": form
            }, status=400)

    return render(request, "courier/index.html", {
        "title": "New Profile",
        "form": RegisterForm()
    })


class NewShipmentForm(forms.Form):
    user_receiver_id = forms.ChoiceField(required=True, label="Select recipient:",
                                         widget=forms.Select(
                                             attrs={"class": "form-control", "placeholder": "User name to select"}))

capstone/courier/templates/courier/index.html
{% extends "courier/layout.html" %}
{% load static %}

{% block nav %}
    {% include 'courier/nav.html' %}
{% endblock %}

{% block script %}
    {% if title == 'User Profile' %}
        <script src="{% static 'courier/gps.js' %}"></script>
        <script src="{% static 'courier/profile.js' %}"></script>
    {% elif title == 'New Shipment' %}
        <script type="module" src="{% static 'courier/new_ship.js' %}"></script>
    {% else %}
        <script type="module" src="{% static 'courier/shipments.js' %}"></script>
    {% endif %}
{% endblock %}


{% block body %}
    {% if title == 'New Shipment' %}
        {% include 'courier/new_ship.html' %}
    {% elif title == 'User Profile' %}
        {% include 'courier/profile.html' %}
    {% elif title == 'New Profile' %}
        {% include 'courier/register.html' %}
    {% else %}
        {% include 'courier/shipments.html' %}
    {% endif %}

{% endblock %}

capstone/courier/templates/courier/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{{ title }}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'courier/styles.css' %}" rel="stylesheet">
        {% block script %}
        {% endblock %}
    </head>
<body class="body-base body-layout">
        {% block nav %}
        {% endblock %}
            {% block body %}
            {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

capstone/courier/templates/courier/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Login</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'courier/styles.css' %}" rel="stylesheet">
    </head>
    <body class="body-base body-log">
        <form action="{% url 'login' %}" method="post" class="form-login">
            {% csrf_token %}
            <h1 class="h3 mb-3 font-weight-normal">Login</h1>
            {{form.as_p}}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
            {% if message %}
                <hr>
                <div class="alert alert-danger" role="alert" id="message"><p>{{ message }}</p></div>
            {% endif %}
            <p>Don't have an account? <a href="{% url 'register' %}">Register here.</a></p>
        </form>
    </body>
</html>

capstone/courier/templates/courier/nav.html
<nav class="navbar navbar-expand-md navbar-light bg-light">
    {% if user.is_authenticated %}
      <a class="navbar-brand mb-0 h1" href="{% url 'index' %}">Courier System: </a>
      <a id="user-name" class="navbar-brand mb-0 h1" href="{% url 'profile' %}">{{ user.username }}</a>
    {% else %}
        <a class="navbar-brand mb-0 h1" href="{% url 'index' %}">Courier System</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle {% if title == 'New Shipment' or title == 'Courier System' %} active{% endif %}" href="{% url 'index' %}" id="Shipment_navbarDropdown"
                   role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Shipment</a>
                <div class="dropdown-menu" aria-labelledby="Shipment_navbarDropdown">
                  <a class="dropdown-item" href="{% url 'index' %}">View Shipments</a>
                    <a class="dropdown-item" href="{% url 'new-shipment' %}">New Shipment</a>
                    <a class="dropdown-item" href="{% url 'receipt-shipment' %}">Shipment to Receipt</a>
                    <a class="dropdown-item" href="{% url 'deliver-shipment' %}">Shipment to Deliver</a>
                </div>
            </li>
            {% if is_courier %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if title == 'Courier View' or title == 'Register Receipt' or title == 'Register Deliver' %} active{% endif %}" href="{% url 'courier-view' %}" id="shipments_navbarDropdown"
                       role="button" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">Courier</a>
                    <div class="dropdown-menu" aria-labelledby="shipments_navbarDropdown">
                        <a class="dropdown-item" href="{% url 'courier-view' %}">All Shipments</a>
                        <a class="dropdown-item" href="{% url 'courier-order' %}">Shipments to order</a>
                        <a class="dropdown-item" href="{% url 'courier-receive' %}">Order to receive</a>
                        <a class="dropdown-item" href="{% url 'courier-deliver' %}">Order to deliver</a>
                        <a class="dropdown-item" href="{% url 'courier-delivered' %}">Delivered Orders</a>
                    </div>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link {% if title == 'User Profile' %} active{% endif %}" href="{% url 'profile' %}">User Profile</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
      </ul>
    </div>
</nav>
<h1 id="page_title"></h1>

capstone/courier/templates/courier/new_ship.html
<div class="div_profile">
    <h1 class="h3 mb-3 font-weight-normal">Create New Shipment</h1>
    <form action="{% url 'new-shipment' %}" method="post" class="form-register" id="new-shipment_form">
        {% csrf_token %}
        {% for field in form %}
            {% if field.errors %}
                {{ field.errors }}
            {% endif %}
            {% if field.name == 'user_receiver_id' %}
                <div class="form-group">
                    <label for="id_user_receiver_id">Select user for delivery:</label>
                    <input type="text" name="search-user" class="form-control" placeholder="Filter options in select user" autofocus id="search-user">
                    {{ field }}
                </div>
            {% else %}
                {{ field }}
            {% endif %}
        {% endfor %}

        <div id="address_sender-select">
        </div>
        <div id="address_deliver-select">
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit" id="button-submit">Create</button>
        {% if message %}
            <hr>
            <div class="alert alert-danger" role="alert" id="message"><p>{{ message }}</p></div>
        {% endif %}
    </form>
</div>

capstone/courier/templates/courier/register.html
{% load static %}

{% if message %}
    <hr>
    <div class="alert alert-danger" role="alert" id="message"><p>{{ message|safe }}</p></div>
{% endif %}

<form action="{% url 'register' %}" method="post" class="form-register">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Register</h1>
    {% for field in form %}
        {% if field.name == 'gps_latitude' %}
            <div class="div_gps">
                {% if form.errors.gps_latitude %}
                    {{ form.errors.gps_latitude }}
                {% endif %}
                {{ form.gps_latitude }}
        {% else %}
            {% if field.name == 'gps_longitude' %}
                    {% if form.errors.gps_longitude %}
                        {{ form.errors.gps_longitude }}
                    {% endif %}
                    {{ form.gps_longitude }}
                    <button type="button" class="btn btn-sm btn-outline-info" id="get_gps_pos">GPS</button>
                </div>
            {% else %}
                <div>
                    {% if field.name == 'is_courier' %}
                        {% if field.errors %}
                            {{ field.errors }}
                        {% endif %}
                        {{ field }} Is courier
                    {% else %}
                        {% if field.errors %}
                            {{ field.errors }}
                        {% endif %}
                        {{ field }}
                    {% endif %}
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    <button class="btn btn-lg btn-primary btn-block" type="submit" id="message">Register</button>
    {% if message %}
        <hr>
        <div class="alert alert-danger" role="alert"><p>{{ message|safe }}</p></div>
    {% endif %}
    {% if not user.is_authenticated %}
        <p>Already have an account? <a href="{% url 'login' %}">Log In here.</a></p>
    {% endif %}
</form>

capstone/courier/templates/courier/shipments.html
{% if message %}
    <hr>
    <div class="alert alert-danger" role="alert" id="message"><p>{{ message }}</p></div>
{% endif %}

{% for ship in shipments %}
    <div class="div_shipments" title="Click to view all informations.">
        <ul class="ul_shipments">
            {% if title != 'Courier System'  %}
                <li><b>From user:</b> {{ ship.user_sender.username }}
                    <ul class="hide">
                        <li><b>First name:</b> {{ ship.user_sender.first_name }}</li>
                        <li><b>Last name:</b> {{ ship.user_sender.last_name }}</li>
                    </ul>
                </li>
            {% endif %}
            <li><b>To user:</b> {{ ship.user_receiver.username }}
                <ul class="hide">
                    <li><b>First name:</b> {{ ship.user_receiver.first_name }}</li>
                    <li><b>Last name:</b> {{ ship.user_receiver.last_name }}</li>
                </ul>
            </li>
            <li><b>Content:</b> {{ ship.contents }}</li>
            <li class="hide">
                <hr>
                <b>Address to get:</b>
                <ul>
                    <li><b>Address:</b> {{ ship.address_sender.address }}</li>
                    <li><b>Complement:</b> {{ ship.address_sender.complement }}</li>
                    <li><b>City:</b> {{ ship.address_sender.city }}</li>
                    {% if ship.address_sender.gps %}
                    <li><b>GPS position:</b> ({{ ship.address_sender.gps.latitude }}, {{ ship.address_sender.gps.longitude }})</li>
                    {% endif %}
                </ul>
            </li>
            <li class="hide">
                <hr>
                <b>Address to deliver:</b>
                <ul>
                    <li><b>Address:</b> {{ ship.address_receiver.address }}</li>
                    <li><b>Complement:</b> {{ ship.address_receiver.complement }}</li>
                    <li><b>City:</b> {{ ship.address_receiver.city }}</li>
                    {% if ship.address_receiver.gps %}
                    <li><b>GPS position:</b> ({{ ship.address_receiver.gps.latitude }}, {{ ship.address_receiver.gps.longitude }})</li>
                    {% endif %}
                </ul>
            </li>
            {% if title in 'All Shipments Shipments to order Order to receive Order to deliver'  %}
                    <!--Shipment.CREATED-->
                    {% if ship.status_id == 0 %}
                        <form action="{% url 'courier-order' %}" method="post" class="form-courier">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-primary" type="submit">Order</button>
                            <input type="hidden" name="shipment_id" value="{{ ship.id }}">
                        </form>

                    <!--Shipment.ORDERED-->
                    {% elif ship.status_id == 1 %}
                        <form action="{% url 'courier-receive' %}" method="post" class="div_gps">
                            {% csrf_token %}
                            <input type="text" name="check_code_get" maxlength="4" required placeholder="Check code" id="id_check_code_get">
                            &nbsp;
                            <button class="btn btn-sm btn-warning" type="submit">Received</button>
                            <input type="hidden" name="shipment_id" value="{{ ship.id }}">
                        </form>
                    <!--Shipment.PICK_UP-->
                    {% elif ship.status_id == 2 %}
                        <form action="{% url 'courier-deliver' %}" method="post" class="div_gps">
                            {% csrf_token %}
                            <input type="text" name="check_code_put" maxlength="4" required placeholder="Check code" id="id_check_code_put">
                            <button class="btn btn-sm btn-success" type="submit">Delivered</button>
                            <input type="hidden" name="shipment_id" value="{{ ship.id }}">
                        </form>
                    <!--Shipment.DELIVERED-->
                    {% elif ship.status_id == 3 %}
                        <li><b>Status:</b> {{ ship.status }} </li>
                    {% endif %}
                    <input type="hidden" name="shipment_id" value="{{ ship.id }}">
                </form>
            {% else %}
                <li><b>Status:</b> {{ ship.status }} </li>
            {% endif %}
            {% if user.username == ship.user_receiver.username %}
                <li><b>Check code:</b> {{ ship.check_code_put }} </li>
            {% endif %}
            {% if user.username == ship.user_sender.username %}
                <li><b>Check code:</b> {{ ship.check_code_get }} </li>
            {% endif %}
            {% if ship.user_sender.id == user.id and ship.status_id == 0 %}
                <form action="{% url 'cancel-shipment' %}" method="post" class="form-courier">
                    {% csrf_token %}
                    <button class="btn btn-sm btn-danger" type="submit">Cancel</button>
                    <input type="hidden" name="shipment_id" value="{{ ship.id }}">
                </form>
            {% endif %}
        </ul>
    </div>
{% empty %}
    <h1>No shipments for user {{ user.username }} is provided</h1>
{% endfor %}